### ISSUE TITLE
Can't use pd.read_sql with db.engine anymore (sqlalchemy breaking change)

### ISSUE THREAD

**Issue by larsschellhas** [OpenEnergyPlatform/open-MaStR#435]
## Description of the issue

When running 

```
db = Mastr()
table="wind_extended"
df = pd.read_sql(sql=table, con=db.engine)
```

I get the following errors:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 4
      1 # Calculate total capacity by technology
      3 table="wind_extended"
----> 4 df = pd.read_sql(sql=table, con=db.engine)

File [c:\Users\XXXXX\Git-Repositories\GER-EMQA-Scripts\.venv\lib\site-packages\pandas\io\sql.py:581](file:///C:/Users/XXXXX/Git-Repositories/GER-EMQA-Scripts/.venv/lib/site-packages/pandas/io/sql.py:581), in read_sql(sql, con, index_col, coerce_float, params, parse_dates, columns, chunksize)
    579 if _is_table_name:
    580     pandas_sql.meta.reflect(bind=pandas_sql.connectable, only=[sql])
--> 581     return pandas_sql.read_table(
    582         sql,
    583         index_col=index_col,
    584         coerce_float=coerce_float,
    585         parse_dates=parse_dates,
    586         columns=columns,
    587         chunksize=chunksize,
    588     )
    589 else:
    590     return pandas_sql.read_query(
    591         sql,
    592         index_col=index_col,
   (...)
    596         chunksize=chunksize,
    597     )
...
   1403 def execute(self, *args, **kwargs):
   1404     """Simple passthrough to SQLAlchemy connectable"""
-> 1405     return self.connectable.execution_options().execute(*args, **kwargs)

AttributeError: 'OptionEngine' object has no attribute 'execute'
```

## Ideas of solution

The error is caused due to sqlalchemy only accepting Connections and no Engines anymore.
Pandas is already deprecating the ability to hand over anything else than a connection, so we should provide a connection object instead of the engine in the future.

## Context and Environment
* Version used: 0.13.0
* Operating system: Windows 10 
* Environment setup and (python) version: Python 3.10, Virtual env. Poetry.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)

**Comment by larsschellhas** [comment]
# Current workaround is to downgrade sqlalchemy to <2.0

**Comment by FlorianK13** [comment]
Hi @larsschellhas this is a problem that I also ran into already. 'Pandas' is not yet compatible with 'SQLalchemy' >= 2.0 and I hope they resolve it soon.

**Comment by larsschellhas** [comment]
Apparently they will deprecate the ability to provide an engine instead of a connection however.
So, we should make sure this Plugin uses a connection instead of an engine (if that's how it is implemented atm.

**Comment by deniztepe** [comment]
The module itself works with sqlalchemy 2.0. We migrated to passing a connection down. I would suggest not to provide a connection object derived from the engine, as the connection supposed to be used on the fly and not static, as far as I know. An option for the end user is to do the following:
```
db = Mastr()
table="wind_extended"
with engine.connect() as con:
    with con.begin():
       df = pd.read_sql(sql=table, con=con)
```
This adds two lines of overhead, i agree, but keeps the open-mastr module less dependent.

The documentation at https://open-mastr.readthedocs.io/en/latest/getting_started.html#accessing-the-database should definitely be updated, accordingly.

**Comment by FlorianK13** [comment]
@deniztepe This has not be done yet, right?

**Comment by deniztepe** [comment]
No, as I said, I would suggest to edit only the documentation.

**Comment by FlorianK13** [comment]
I see, the problem is not when downloading the MaStR, but when accessing it. I will update the documentation accordingly.

**Comment by FlorianK13** [comment]
@larsschellhas In Pandas 2.0 they have worked on this issue, so using pandas >=2.0 should resolve it. See https://github.com/pandas-dev/pandas/issues/40686
